spring.application.name=FourLoop

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/tekken;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=chris
spring.datasource.password=root
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Data Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.check-template-location=true